version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  frontend:
    build: ./frontend
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
    env_file:
      - .env
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=${MY_IP}
    depends_on:
      - backend

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bloomday123
      MYSQL_DATABASE: proyecto_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: